In [10]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('input.txt', header=None)

In [9]:
matrix = data.values + data.values.T

In [11]:
np.where(matrix == 2020)

(array([ 20, 186]), array([186,  20]))

In [13]:
data.iloc[20] * data.iloc[186]

0    633216
dtype: int64

In [14]:
vec = data.values

In [28]:
mat_three = (vec[:, :, np.newaxis] + vec[:, :, np.newaxis].T + np.swapaxes(vec[:, :, np.newaxis], 0, 1))

In [29]:
np.where(mat_three == 2020)

(array([ 68,  68, 149, 149, 168, 168]),
 array([149, 168,  68, 168,  68, 149]),
 array([168, 149, 168,  68, 149,  68]))

In [31]:
vec[168] * vec[68] * vec[149]

array([68348924])